### ISSUE TITLE
Implement unit testing on CVI/ICVIs

### ISSUE THREAD

**Issue by AP6YC** [AP6YC/cvi#1]

**Comment by nikmelton** [comment]
Add a unit test to check batch and incremental version return the same results and another test to make sure incremental is running faster than batch. Need this for every CVI

**Comment by AP6YC** [comment]
> Add a unit test to check batch and incremental version return the same results and another test to make sure incremental is running faster than batch. Need this for every CVI

Good suggestion. I created issue #5 for that. Closing this issue since bare-bones unit tests are setup.
